# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-26 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='info',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
